/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ReembolsosRouteImport } from './routes/reembolsos'
import { Route as PropiedadIntelectualRouteImport } from './routes/propiedad-intelectual'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetodoIndexRouteImport } from './routes/metodo.index'
import { Route as MetodoSlugRouteImport } from './routes/metodo.$slug'
import { Route as ApiPublicWebhookMpRouteImport } from './routes/api/public/webhook-mp'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsosRoute = ReembolsosRouteImport.update({
  id: '/reembolsos',
  path: '/reembolsos',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadIntelectualRoute = PropiedadIntelectualRouteImport.update({
  id: '/propiedad-intelectual',
  path: '/propiedad-intelectual',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoIndexRoute = MetodoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetodoRoute,
} as any)
const MetodoSlugRoute = MetodoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MetodoRoute,
} as any)
const ApiPublicWebhookMpRoute = ApiPublicWebhookMpRouteImport.update({
  id: '/api/public/webhook-mp',
  path: '/api/public/webhook-mp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/gracias': typeof GraciasRoute
  '/metodo': typeof MetodoRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/propiedad-intelectual': typeof PropiedadIntelectualRoute
  '/reembolsos': typeof ReembolsosRoute
  '/terminos': typeof TerminosRoute
  '/metodo/$slug': typeof MetodoSlugRoute
  '/metodo/': typeof MetodoIndexRoute
  '/api/public/webhook-mp': typeof ApiPublicWebhookMpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/gracias': typeof GraciasRoute
  '/privacidad': typeof PrivacidadRoute
  '/propiedad-intelectual': typeof PropiedadIntelectualRoute
  '/reembolsos': typeof ReembolsosRoute
  '/terminos': typeof TerminosRoute
  '/metodo/$slug': typeof MetodoSlugRoute
  '/metodo': typeof MetodoIndexRoute
  '/api/public/webhook-mp': typeof ApiPublicWebhookMpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/gracias': typeof GraciasRoute
  '/metodo': typeof MetodoRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/propiedad-intelectual': typeof PropiedadIntelectualRoute
  '/reembolsos': typeof ReembolsosRoute
  '/terminos': typeof TerminosRoute
  '/metodo/$slug': typeof MetodoSlugRoute
  '/metodo/': typeof MetodoIndexRoute
  '/api/public/webhook-mp': typeof ApiPublicWebhookMpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/gracias'
    | '/metodo'
    | '/privacidad'
    | '/propiedad-intelectual'
    | '/reembolsos'
    | '/terminos'
    | '/metodo/$slug'
    | '/metodo/'
    | '/api/public/webhook-mp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/gracias'
    | '/privacidad'
    | '/propiedad-intelectual'
    | '/reembolsos'
    | '/terminos'
    | '/metodo/$slug'
    | '/metodo'
    | '/api/public/webhook-mp'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/gracias'
    | '/metodo'
    | '/privacidad'
    | '/propiedad-intelectual'
    | '/reembolsos'
    | '/terminos'
    | '/metodo/$slug'
    | '/metodo/'
    | '/api/public/webhook-mp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  GraciasRoute: typeof GraciasRoute
  MetodoRoute: typeof MetodoRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  PropiedadIntelectualRoute: typeof PropiedadIntelectualRoute
  ReembolsosRoute: typeof ReembolsosRoute
  TerminosRoute: typeof TerminosRoute
  ApiPublicWebhookMpRoute: typeof ApiPublicWebhookMpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolsos': {
      id: '/reembolsos'
      path: '/reembolsos'
      fullPath: '/reembolsos'
      preLoaderRoute: typeof ReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedad-intelectual': {
      id: '/propiedad-intelectual'
      path: '/propiedad-intelectual'
      fullPath: '/propiedad-intelectual'
      preLoaderRoute: typeof PropiedadIntelectualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo/': {
      id: '/metodo/'
      path: '/'
      fullPath: '/metodo/'
      preLoaderRoute: typeof MetodoIndexRouteImport
      parentRoute: typeof MetodoRoute
    }
    '/metodo/$slug': {
      id: '/metodo/$slug'
      path: '/$slug'
      fullPath: '/metodo/$slug'
      preLoaderRoute: typeof MetodoSlugRouteImport
      parentRoute: typeof MetodoRoute
    }
    '/api/public/webhook-mp': {
      id: '/api/public/webhook-mp'
      path: '/api/public/webhook-mp'
      fullPath: '/api/public/webhook-mp'
      preLoaderRoute: typeof ApiPublicWebhookMpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MetodoRouteChildren {
  MetodoSlugRoute: typeof MetodoSlugRoute
  MetodoIndexRoute: typeof MetodoIndexRoute
}

const MetodoRouteChildren: MetodoRouteChildren = {
  MetodoSlugRoute: MetodoSlugRoute,
  MetodoIndexRoute: MetodoIndexRoute,
}

const MetodoRouteWithChildren =
  MetodoRoute._addFileChildren(MetodoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  GraciasRoute: GraciasRoute,
  MetodoRoute: MetodoRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  PropiedadIntelectualRoute: PropiedadIntelectualRoute,
  ReembolsosRoute: ReembolsosRoute,
  TerminosRoute: TerminosRoute,
  ApiPublicWebhookMpRoute: ApiPublicWebhookMpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
