/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ReembolsosRouteImport } from './routes/reembolsos'
import { Route as RecuperarContrasenaRouteImport } from './routes/recuperar-contrasena'
import { Route as PropiedadIntelectualRouteImport } from './routes/propiedad-intelectual'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetodoIndexRouteImport } from './routes/metodo.index'
import { Route as MetodoSlugRouteImport } from './routes/metodo.$slug'
import { Route as AuthenticatedProgresoRouteImport } from './routes/_authenticated/progreso'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsosRoute = ReembolsosRouteImport.update({
  id: '/reembolsos',
  path: '/reembolsos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarContrasenaRoute = RecuperarContrasenaRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadIntelectualRoute = PropiedadIntelectualRouteImport.update({
  id: '/propiedad-intelectual',
  path: '/propiedad-intelectual',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoIndexRoute = MetodoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetodoRoute,
} as any)
const MetodoSlugRoute = MetodoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MetodoRoute,
} as any)
const AuthenticatedProgresoRoute = AuthenticatedProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/metodo': typeof MetodoRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/propiedad-intelectual': typeof PropiedadIntelectualRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/reembolsos': typeof ReembolsosRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/metodo/$slug': typeof MetodoSlugRoute
  '/metodo/': typeof MetodoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/privacidad': typeof PrivacidadRoute
  '/propiedad-intelectual': typeof PropiedadIntelectualRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/reembolsos': typeof ReembolsosRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/metodo/$slug': typeof MetodoSlugRoute
  '/metodo': typeof MetodoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aviso-legal': typeof AvisoLegalRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/metodo': typeof MetodoRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/propiedad-intelectual': typeof PropiedadIntelectualRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/reembolsos': typeof ReembolsosRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/progreso': typeof AuthenticatedProgresoRoute
  '/metodo/$slug': typeof MetodoSlugRoute
  '/metodo/': typeof MetodoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/iniciar-sesion'
    | '/metodo'
    | '/privacidad'
    | '/propiedad-intelectual'
    | '/recuperar-contrasena'
    | '/reembolsos'
    | '/registro'
    | '/reset-password'
    | '/terminos'
    | '/admin'
    | '/configuracion'
    | '/perfil'
    | '/progreso'
    | '/metodo/$slug'
    | '/metodo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/iniciar-sesion'
    | '/privacidad'
    | '/propiedad-intelectual'
    | '/recuperar-contrasena'
    | '/reembolsos'
    | '/registro'
    | '/reset-password'
    | '/terminos'
    | '/admin'
    | '/configuracion'
    | '/perfil'
    | '/progreso'
    | '/metodo/$slug'
    | '/metodo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aviso-legal'
    | '/iniciar-sesion'
    | '/metodo'
    | '/privacidad'
    | '/propiedad-intelectual'
    | '/recuperar-contrasena'
    | '/reembolsos'
    | '/registro'
    | '/reset-password'
    | '/terminos'
    | '/_authenticated/admin'
    | '/_authenticated/configuracion'
    | '/_authenticated/perfil'
    | '/_authenticated/progreso'
    | '/metodo/$slug'
    | '/metodo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AvisoLegalRoute: typeof AvisoLegalRoute
  IniciarSesionRoute: typeof IniciarSesionRoute
  MetodoRoute: typeof MetodoRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  PropiedadIntelectualRoute: typeof PropiedadIntelectualRoute
  RecuperarContrasenaRoute: typeof RecuperarContrasenaRoute
  ReembolsosRoute: typeof ReembolsosRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolsos': {
      id: '/reembolsos'
      path: '/reembolsos'
      fullPath: '/reembolsos'
      preLoaderRoute: typeof ReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedad-intelectual': {
      id: '/propiedad-intelectual'
      path: '/propiedad-intelectual'
      fullPath: '/propiedad-intelectual'
      preLoaderRoute: typeof PropiedadIntelectualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo/': {
      id: '/metodo/'
      path: '/'
      fullPath: '/metodo/'
      preLoaderRoute: typeof MetodoIndexRouteImport
      parentRoute: typeof MetodoRoute
    }
    '/metodo/$slug': {
      id: '/metodo/$slug'
      path: '/$slug'
      fullPath: '/metodo/$slug'
      preLoaderRoute: typeof MetodoSlugRouteImport
      parentRoute: typeof MetodoRoute
    }
    '/_authenticated/progreso': {
      id: '/_authenticated/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AuthenticatedProgresoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProgresoRoute: typeof AuthenticatedProgresoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProgresoRoute: AuthenticatedProgresoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MetodoRouteChildren {
  MetodoSlugRoute: typeof MetodoSlugRoute
  MetodoIndexRoute: typeof MetodoIndexRoute
}

const MetodoRouteChildren: MetodoRouteChildren = {
  MetodoSlugRoute: MetodoSlugRoute,
  MetodoIndexRoute: MetodoIndexRoute,
}

const MetodoRouteWithChildren =
  MetodoRoute._addFileChildren(MetodoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AvisoLegalRoute: AvisoLegalRoute,
  IniciarSesionRoute: IniciarSesionRoute,
  MetodoRoute: MetodoRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  PropiedadIntelectualRoute: PropiedadIntelectualRoute,
  RecuperarContrasenaRoute: RecuperarContrasenaRoute,
  ReembolsosRoute: ReembolsosRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
